name: Arcadible Release

on:
  workflow_call:

permissions:
  contents: write

env:
  # repo
  ARC_NAME: ${{ github.event.repository.name }}
  ARC_SHA: ${{ github.sha }}
  ARC_TAG: ${{ github.ref_name }}
  # work
  ARC_BIN: ${{ github.workspace }}/node_modules/.bin
  ARC_DIST: ${{ github.workspace }}/.arcadible/dist
  ARC_JSON: ${{ github.workspace }}/package.json
  ARC_TOML: ${{ github.workspace }}/arcadible.toml

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      # repo
      prerelease: ${{ steps.sh.outputs.prerelease }}
      # work
      deploy_dir: ${{ steps.sh.outputs.deploy_dir }}
      skip_build: ${{ steps.sh.outputs.skip_build }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install
        run: npm install @arcadible/cicd-github-release@^0.0.1 --no-save
      - name: Check TOML
        run: |
          $ARC_BIN/arctk-assert-file "$ARC_TOML"
          $ARC_BIN/arctk-assert-toml "$ARC_TOML"
      - name: Check Tag
        run: $ARC_BIN/arctk-assert-tag "$ARC_TAG"
      - name: Output
        id: sh
        run: |
          # repo
          $ARC_BIN/arctk-prerelease "$ARC_TAG"
          # work
          $ARC_BIN/arctk-deploy-dir "$ARC_TOML"
          $ARC_BIN/arctk-skip-build "$ARC_TOML"
  build:
    needs: [setup]
    runs-on: ubuntu-latest
    env:
      ARC_BUILD: ${{ github.workspace }}/${{ needs.setup.outputs.deploy_dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install
        if: needs.setup.outputs.skip_build == 'false'
        run: |
          npm ci
          npm install @arcadible/cicd-github-release@^0.0.1 --no-save
      - name: Build
        if: needs.setup.outputs.skip_build == 'false'
        run: $ARC_BIN/arctk-build "$ARC_JSON"
      - name: Reinstall
        if: needs.setup.outputs.skip_build == 'true'
        run: npm install @arcadible/cicd-github-release@^0.0.1 --no-save
      - name: Check Build
        run: $ARC_BIN/arctk-assert-dir "$ARC_BUILD"
      - name: Dist
        run: $ARC_BIN/arctk-dist "$ARC_DIST" "$ARC_BUILD" "$ARC_TOML" "$ARC_NAME" "$ARC_TAG"
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ${{ env.ARC_DIST }}
  publish:
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ${{ env.ARC_DIST }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.ARC_NAME }} ${{ env.ARC_TAG }}
          prerelease: ${{ needs.setup.outputs.prerelease }}
          target_commitish: ${{ env.ARC_SHA }}
          files: ${{ env.ARC_DIST }}/*
